-- AutoSyndicate: Carbon District — Supabase schema v9
-- Run AFTER schema_v8.sql in Supabase SQL Editor.
-- Requires Anonymous Sign-Ins enabled in Authentication -> Providers.

begin;
create extension if not exists pgcrypto;

-- ==================== EXTENDED PLAYER PROFILES ====================
alter table public.player_profiles add column if not exists telegram_username text;
alter table public.player_profiles add column if not exists best_0_100 numeric(7,3);
alter table public.player_profiles add column if not exists current_car_name text;
alter table public.player_profiles add column if not exists rating integer not null default 0;
create index if not exists player_profiles_username_idx on public.player_profiles(lower(telegram_username)) where telegram_username is not null;
create index if not exists player_profiles_rating_idx on public.player_profiles(rating desc,wins desc);

create or replace function public.autosyndicate_profile_guard()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_db_admin boolean := session_user in ('postgres', 'supabase_admin');
  v_jwt_role text := coalesce(
    current_setting('request.jwt.claim.role', true),
    case when nullif(current_setting('request.jwt.claims', true), '') is not null
      then (current_setting('request.jwt.claims', true)::jsonb ->> 'role') else null end,
    ''
  );
begin
  if v_uid is null and not v_db_admin and v_jwt_role <> 'service_role' then
    raise exception 'authentication required';
  end if;

  if tg_op='INSERT' then
    if v_uid is not null then new.owner_uid:=v_uid;
    elsif new.owner_uid is null then raise exception 'owner_uid is required for privileged insert';
    end if;
  else
    if not v_db_admin and v_jwt_role <> 'service_role' then
      if old.owner_uid is null or old.owner_uid<>v_uid then raise exception 'profile is not owned by current session'; end if;
    end if;
    new.id:=old.id;new.owner_uid:=old.owner_uid;
  end if;

  new.id:=left(trim(coalesce(new.id,'')),90);
  if new.id !~ '^(tg_[0-9]{1,24}|guest_[A-Za-z0-9-]{8,80})$' then raise exception 'invalid player id'; end if;
  new.name:=left(regexp_replace(trim(coalesce(new.name,'Гонщик')),'[[:cntrl:]]','','g'),48);
  if new.name='' then new.name:='Гонщик'; end if;
  if new.photo_url is not null and new.photo_url !~ '^https://[^[:space:]]+$' then new.photo_url:=null; end if;
  new.telegram_username:=nullif(left(regexp_replace(trim(leading '@' from coalesce(new.telegram_username,'')),'[^A-Za-z0-9_]','','g'),32),'');
  new.level:=greatest(1,least(coalesce(new.level,1),500));
  new.balance:=greatest(0,least(coalesce(new.balance,0),1000000000000));
  new.xp:=greatest(0,least(coalesce(new.xp,0),2000000000));
  new.races:=greatest(0,least(coalesce(new.races,0),2000000000));
  new.wins:=greatest(0,least(coalesce(new.wins,0),new.races));
  new.losses:=greatest(0,least(coalesce(new.losses,0),new.races));
  new.total_earned:=greatest(0,least(coalesce(new.total_earned,0),1000000000000));
  new.best_0_100:=case when new.best_0_100 is null or new.best_0_100<=0 then null else greatest(0.500,least(new.best_0_100,120.000)) end;
  new.current_car_name:=nullif(left(regexp_replace(trim(coalesce(new.current_car_name,'')),'[[:cntrl:]]','','g'),60),'');
  new.rating:=greatest(0,least(coalesce(new.rating,0),2000000000));
  if cardinality(coalesce(new.owned_cars,'{}'::integer[]))>100 then new.owned_cars:=new.owned_cars[1:100]; end if;
  new.active_car_id:=greatest(1,least(coalesce(new.active_car_id,1),100000));
  new.last_seen:=now();
  return new;
end;
$$;

drop trigger if exists trg_autosyndicate_profile_guard on public.player_profiles;
create trigger trg_autosyndicate_profile_guard before insert or update on public.player_profiles
for each row execute function public.autosyndicate_profile_guard();

-- ==================== FRIENDS ====================
create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_uid uuid not null references auth.users(id) on delete cascade,
  recipient_uid uuid not null references auth.users(id) on delete cascade,
  requester_id text not null references public.player_profiles(id) on delete cascade,
  recipient_id text not null references public.player_profiles(id) on delete cascade,
  requester_name text not null,
  recipient_name text not null,
  status text not null default 'pending' check(status in ('pending','accepted')),
  created_at timestamptz not null default now(),
  responded_at timestamptz
);
create unique index if not exists friendships_pair_unique_idx on public.friendships(
  least(requester_uid::text,recipient_uid::text),greatest(requester_uid::text,recipient_uid::text)
);
create index if not exists friendships_requester_idx on public.friendships(requester_uid,status,id desc);
create index if not exists friendships_recipient_idx on public.friendships(recipient_uid,status,id desc);
alter table public.friendships enable row level security;
drop policy if exists friendships_select_participants on public.friendships;
create policy friendships_select_participants on public.friendships for select to authenticated
using(requester_uid=auth.uid() or recipient_uid=auth.uid());
grant select on public.friendships to authenticated;

create or replace function public.autosyndicate_send_friend_request(p_query text)
returns bigint
language plpgsql security definer set search_path=public
as $$
declare me public.player_profiles%rowtype; target public.player_profiles%rowtype; rid bigint; q text;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  select * into me from public.player_profiles where owner_uid=auth.uid() limit 1;
  if me.id is null then raise exception 'profile sync required'; end if;
  q:=left(trim(leading '@' from trim(coalesce(p_query,''))),90);
  if q='' then raise exception 'player id or telegram login required'; end if;
  select * into target from public.player_profiles
    where id=q or lower(coalesce(telegram_username,''))=lower(q)
    order by case when id=q then 0 else 1 end,last_seen desc limit 1;
  if target.id is null then raise exception 'player not found'; end if;
  if target.owner_uid=auth.uid() then raise exception 'cannot add yourself'; end if;
  if exists(select 1 from public.friendships where (requester_uid=auth.uid() and recipient_uid=target.owner_uid) or (requester_uid=target.owner_uid and recipient_uid=auth.uid())) then
    raise exception 'friendship already exists';
  end if;
  insert into public.friendships(requester_uid,recipient_uid,requester_id,recipient_id,requester_name,recipient_name)
  values(auth.uid(),target.owner_uid,me.id,target.id,me.name,target.name) returning id into rid;
  return rid;
end;$$;

grant execute on function public.autosyndicate_send_friend_request(text) to authenticated;

create or replace function public.autosyndicate_accept_friend_request(p_friendship_id bigint)
returns boolean
language plpgsql security definer set search_path=public
as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  update public.friendships set status='accepted',responded_at=now()
    where id=p_friendship_id and recipient_uid=auth.uid() and status='pending';
  if not found then raise exception 'friend request not found'; end if;
  return true;
end;$$;
grant execute on function public.autosyndicate_accept_friend_request(bigint) to authenticated;

create or replace function public.autosyndicate_remove_friendship(p_friendship_id bigint)
returns boolean
language plpgsql security definer set search_path=public
as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  delete from public.friendships where id=p_friendship_id and (requester_uid=auth.uid() or recipient_uid=auth.uid());
  if not found then raise exception 'friendship not found'; end if;
  return true;
end;$$;
grant execute on function public.autosyndicate_remove_friendship(bigint) to authenticated;

-- ==================== CLANS ====================
create table if not exists public.clans (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  owner_uid uuid not null references auth.users(id) on delete cascade,
  owner_id text not null references public.player_profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);
create unique index if not exists clans_name_unique_idx on public.clans(lower(name));
create index if not exists clans_owner_idx on public.clans(owner_uid);
alter table public.clans enable row level security;
drop policy if exists clans_select_all on public.clans;
create policy clans_select_all on public.clans for select to anon,authenticated using(true);
grant select on public.clans to anon,authenticated;

create table if not exists public.clan_members (
  clan_id uuid not null references public.clans(id) on delete cascade,
  member_uid uuid not null references auth.users(id) on delete cascade,
  player_id text not null references public.player_profiles(id) on delete cascade,
  player_name text not null,
  role text not null default 'member' check(role in ('owner','officer','member')),
  joined_at timestamptz not null default now(),
  primary key(clan_id,member_uid),
  unique(member_uid)
);
create index if not exists clan_members_clan_idx on public.clan_members(clan_id,joined_at);
alter table public.clan_members enable row level security;
drop policy if exists clan_members_select_all on public.clan_members;
create policy clan_members_select_all on public.clan_members for select to anon,authenticated using(true);
grant select on public.clan_members to anon,authenticated;

create table if not exists public.clan_invites (
  id bigint generated by default as identity primary key,
  clan_id uuid not null references public.clans(id) on delete cascade,
  inviter_uid uuid not null references auth.users(id) on delete cascade,
  inviter_name text not null,
  invitee_uid uuid not null references auth.users(id) on delete cascade,
  invitee_id text not null references public.player_profiles(id) on delete cascade,
  status text not null default 'pending' check(status in ('pending','accepted','cancelled')),
  created_at timestamptz not null default now(),
  responded_at timestamptz
);
create unique index if not exists clan_invites_pending_unique_idx on public.clan_invites(clan_id,invitee_uid) where status='pending';
create index if not exists clan_invites_invitee_idx on public.clan_invites(invitee_uid,status,id desc);
alter table public.clan_invites enable row level security;
drop policy if exists clan_invites_select_participants on public.clan_invites;
create policy clan_invites_select_participants on public.clan_invites for select to authenticated
using(invitee_uid=auth.uid() or exists(select 1 from public.clan_members m where m.clan_id=clan_invites.clan_id and m.member_uid=auth.uid() and m.role in ('owner','officer')));
grant select on public.clan_invites to authenticated;

create or replace function public.autosyndicate_create_clan(p_name text)
returns uuid
language plpgsql security definer set search_path=public
as $$
declare me public.player_profiles%rowtype; cid uuid; n text;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  select * into me from public.player_profiles where owner_uid=auth.uid() limit 1;
  if me.id is null then raise exception 'profile sync required'; end if;
  if exists(select 1 from public.clan_members where member_uid=auth.uid()) then raise exception 'already in clan'; end if;
  n:=left(regexp_replace(trim(coalesce(p_name,'')),'[[:cntrl:]]','','g'),24);
  if char_length(n)<3 or n !~ '^[A-Za-zА-Яа-яЁё0-9 _.-]+$' then raise exception 'clan name must be 3-24 characters'; end if;
  insert into public.clans(name,owner_uid,owner_id) values(n,auth.uid(),me.id) returning id into cid;
  insert into public.clan_members(clan_id,member_uid,player_id,player_name,role) values(cid,auth.uid(),me.id,me.name,'owner');
  return cid;
exception when unique_violation then raise exception 'clan name is already taken';
end;$$;
grant execute on function public.autosyndicate_create_clan(text) to authenticated;

create or replace function public.autosyndicate_invite_clan_member(p_query text)
returns bigint
language plpgsql security definer set search_path=public
as $$
declare me public.player_profiles%rowtype; target public.player_profiles%rowtype; cm public.clan_members%rowtype; q text; iid bigint;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  select * into me from public.player_profiles where owner_uid=auth.uid() limit 1;
  select * into cm from public.clan_members where member_uid=auth.uid() and role in ('owner','officer') limit 1;
  if me.id is null or cm.clan_id is null then raise exception 'clan management permission required'; end if;
  q:=left(trim(leading '@' from trim(coalesce(p_query,''))),90);
  select * into target from public.player_profiles where id=q or lower(coalesce(telegram_username,''))=lower(q) order by case when id=q then 0 else 1 end,last_seen desc limit 1;
  if target.id is null then raise exception 'player not found'; end if;
  if target.owner_uid=auth.uid() then raise exception 'cannot invite yourself'; end if;
  if exists(select 1 from public.clan_members where member_uid=target.owner_uid) then raise exception 'player already belongs to a clan'; end if;
  if not exists(select 1 from public.friendships f where f.status='accepted' and ((f.requester_uid=auth.uid() and f.recipient_uid=target.owner_uid) or (f.requester_uid=target.owner_uid and f.recipient_uid=auth.uid()))) then
    raise exception 'only accepted friends can be invited';
  end if;
  insert into public.clan_invites(clan_id,inviter_uid,inviter_name,invitee_uid,invitee_id)
  values(cm.clan_id,auth.uid(),me.name,target.owner_uid,target.id) returning id into iid;
  return iid;
exception when unique_violation then raise exception 'invite already pending';
end;$$;
grant execute on function public.autosyndicate_invite_clan_member(text) to authenticated;

create or replace function public.autosyndicate_accept_clan_invite(p_invite_id bigint)
returns uuid
language plpgsql security definer set search_path=public
as $$
declare inv public.clan_invites%rowtype; me public.player_profiles%rowtype;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if exists(select 1 from public.clan_members where member_uid=auth.uid()) then raise exception 'already in clan'; end if;
  select * into inv from public.clan_invites where id=p_invite_id and invitee_uid=auth.uid() and status='pending' for update;
  if inv.id is null then raise exception 'invite not found'; end if;
  select * into me from public.player_profiles where owner_uid=auth.uid() limit 1;
  if me.id is null then raise exception 'profile sync required'; end if;
  insert into public.clan_members(clan_id,member_uid,player_id,player_name,role) values(inv.clan_id,auth.uid(),me.id,me.name,'member');
  update public.clan_invites set status='accepted',responded_at=now() where id=inv.id;
  update public.clan_invites set status='cancelled',responded_at=now() where invitee_uid=auth.uid() and id<>inv.id and status='pending';
  return inv.clan_id;
end;$$;
grant execute on function public.autosyndicate_accept_clan_invite(bigint) to authenticated;

create or replace function public.autosyndicate_leave_clan()
returns boolean
language plpgsql security definer set search_path=public
as $$
declare cm public.clan_members%rowtype; cnt integer;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  select * into cm from public.clan_members where member_uid=auth.uid() limit 1;
  if cm.clan_id is null then raise exception 'not in clan'; end if;
  if cm.role='owner' then
    select count(*) into cnt from public.clan_members where clan_id=cm.clan_id;
    if cnt>1 then raise exception 'leader must remove members before leaving'; end if;
    delete from public.clans where id=cm.clan_id and owner_uid=auth.uid();
  else
    delete from public.clan_members where clan_id=cm.clan_id and member_uid=auth.uid();
  end if;
  return true;
end;$$;
grant execute on function public.autosyndicate_leave_clan() to authenticated;

create or replace function public.autosyndicate_kick_clan_member(p_member_uid uuid)
returns boolean
language plpgsql security definer set search_path=public
as $$
declare mine public.clan_members%rowtype;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  select * into mine from public.clan_members where member_uid=auth.uid() and role='owner' limit 1;
  if mine.clan_id is null then raise exception 'clan owner permission required'; end if;
  if p_member_uid=auth.uid() then raise exception 'owner cannot kick self'; end if;
  delete from public.clan_members where clan_id=mine.clan_id and member_uid=p_member_uid and role<>'owner';
  if not found then raise exception 'member not found'; end if;
  return true;
end;$$;
grant execute on function public.autosyndicate_kick_clan_member(uuid) to authenticated;

create or replace view public.clan_leaderboard as
with scores as (
  select c.id,c.name,c.owner_id,c.created_at,count(m.member_uid)::integer as members,
         coalesce(sum(greatest(0,p.rating)+greatest(0,p.wins)*25+greatest(1,p.level)*10),0)::bigint as score
  from public.clans c
  left join public.clan_members m on m.clan_id=c.id
  left join public.player_profiles p on p.id=m.player_id
  group by c.id,c.name,c.owner_id,c.created_at
), classified as (
  select s.*,
    case when score<1000 then 'Мантика'
         when score<3000 then 'Бронза'
         when score<7000 then 'Серебро'
         when score<15000 then 'Золото'
         when score<30000 then 'Платина'
         when score<60000 then 'Карбон'
         when score<120000 then 'Элита'
         else 'Легенда' end as division
  from scores s
), ranked as (
  select c.*,
    dense_rank() over(order by score desc,created_at asc) as global_rank,
    dense_rank() over(partition by division order by score desc,created_at asc) as division_rank
  from classified c
)
select * from ranked;
grant select on public.clan_leaderboard to anon,authenticated;

-- ==================== SERVER CASE ROLLS ====================
create table if not exists public.case_pity (
  owner_uid uuid primary key references auth.users(id) on delete cascade,
  bronze integer not null default 0,
  silver integer not null default 0,
  gold integer not null default 0,
  gold_car integer not null default 0,
  updated_at timestamptz not null default now()
);
alter table public.case_pity enable row level security;
drop policy if exists case_pity_select_own on public.case_pity;
create policy case_pity_select_own on public.case_pity for select to authenticated using(owner_uid=auth.uid());
grant select on public.case_pity to authenticated;

create table if not exists public.case_rolls (
  id uuid primary key default gen_random_uuid(),
  owner_uid uuid not null references auth.users(id) on delete cascade,
  player_id text not null references public.player_profiles(id) on delete cascade,
  case_id text not null check(case_id in ('bronze','silver','gold')),
  price integer not null,
  prize jsonb not null,
  created_at timestamptz not null default now(),
  claimed_at timestamptz
);
create index if not exists case_rolls_owner_idx on public.case_rolls(owner_uid,created_at desc);
alter table public.case_rolls enable row level security;
drop policy if exists case_rolls_select_own on public.case_rolls;
create policy case_rolls_select_own on public.case_rolls for select to authenticated using(owner_uid=auth.uid());
grant select on public.case_rolls to authenticated;

create or replace function public.autosyndicate_roll_case(p_case_id text,p_context jsonb default '{}'::jsonb)
returns table(roll_id uuid,price integer,prize jsonb)
language plpgsql security definer set search_path=public
as $$
declare
  me public.player_profiles%rowtype; pity public.case_pity%rowtype;
  v_price integer; v_roll numeric; v_type numeric; v_rarity text; v_type_name text;
  v_amount integer; v_part text; v_car integer; v_label text; v_plate text; v_value integer; v_id uuid;
  v_owned integer[]:='{}'::integer[]; last_roll timestamptz;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  select * into me from public.player_profiles where owner_uid=auth.uid() limit 1;
  if me.id is null then raise exception 'profile sync required'; end if;
  if p_case_id not in ('bronze','silver','gold') then raise exception 'unknown case'; end if;
  v_price:=case p_case_id when 'bronze' then 350 when 'silver' then 1400 else 4500 end;
  -- Serialize rolls per account before checking the cooldown. This closes the
  -- concurrent-request race where two RPCs could both pass the timestamp check.
  insert into public.case_pity(owner_uid) values(auth.uid()) on conflict(owner_uid) do nothing;
  select * into pity from public.case_pity where owner_uid=auth.uid() for update;
  select max(created_at) into last_roll from public.case_rolls where owner_uid=auth.uid();
  if last_roll is not null and last_roll>now()-interval '1.5 seconds' then raise exception 'case rate limit'; end if;

  select coalesce(array_agg(x::int),'{}'::integer[]) into v_owned
  from jsonb_array_elements_text(coalesce(p_context->'owned_cars','[]'::jsonb)) t(x)
  where x ~ '^[0-9]{1,6}$';
  if p_case_id='bronze' then pity.bronze:=pity.bronze+1;
  elsif p_case_id='silver' then pity.silver:=pity.silver+1;
  else pity.gold:=pity.gold+1;pity.gold_car:=pity.gold_car+1;
  end if;

  v_roll:=random()*100;
  if p_case_id='bronze' then
    v_rarity:=case when v_roll<72 then 'common' when v_roll<95 then 'rare' when v_roll<99.7 then 'epic' else 'legendary' end;
    if pity.bronze>=10 and v_rarity='common' then v_rarity:='rare';pity.bronze:=0;end if;
  elsif p_case_id='silver' then
    v_rarity:=case when v_roll<50 then 'common' when v_roll<87 then 'rare' when v_roll<98.8 then 'epic' else 'legendary' end;
    if mod(pity.silver,20)=0 and v_rarity in ('common','rare') then v_rarity:='epic';
    elsif mod(pity.silver,6)=0 and v_rarity='common' then v_rarity:='rare';end if;
  else
    v_rarity:=case when v_roll<35 then 'common' when v_roll<77 then 'rare' when v_roll<97 then 'epic' when v_roll<99.7 then 'legendary' else 'mythic' end;
    if mod(pity.gold,12)=0 and v_rarity in ('common','rare') then v_rarity:='epic';end if;
  end if;

  v_type:=random();
  if p_case_id='gold' and (pity.gold_car>=50 or (v_rarity='legendary' and v_type>.88) or (v_rarity='mythic' and v_type>.70) or v_type>.9965) then
    select g into v_car from generate_series(18,25) g where not(g=any(v_owned)) order by random() limit 1;
    if v_car is not null then
      v_type_name:='car';v_rarity:=case when v_rarity='mythic' then 'mythic' else 'legendary' end;v_label:='RARE VEHICLE #'||v_car::text;pity.gold_car:=0;
    end if;
  end if;

  if v_type_name is null and v_type<.46 then
    v_type_name:='coins';
    v_amount:=round(v_price*(case v_rarity when 'common' then .45+random()*.60 when 'rare' then .9+random()*.8 when 'epic' then 1.5+random()*1.3 when 'legendary' then 2.5+random()*2 else 4+random()*3 end));
    v_label:=v_amount::text||' SYND';
  elsif v_type_name is null and v_type<.75 then
    select x into v_part from jsonb_array_elements_text(coalesce(p_context->'available_parts','[]'::jsonb)) t(x)
      where x in ('engine','turbo','gearbox','tires') order by random() limit 1;
    if v_part is not null then
      v_type_name:='tuning';v_label:=case v_part when 'engine' then 'Двигатель' when 'turbo' then 'Турбо' when 'gearbox' then 'КПП' else 'Шины' end||' · +1 STAGE';
    end if;
  end if;

  if v_type_name is null then
    v_type_name:='plate';
    v_plate:=chr(65+floor(random()*26)::int)||lpad(floor(random()*1000)::int::text,3,'0')||chr(65+floor(random()*26)::int)||chr(65+floor(random()*26)::int);
    v_value:=case v_rarity when 'common' then 250 when 'rare' then 900 when 'epic' then 3500 when 'legendary' then 15000 else 50000 end;
    v_label:=v_plate;
  end if;

  prize:=jsonb_build_object('type',v_type_name,'rarity',v_rarity,'label',v_label);
  if v_type_name='coins' then prize:=prize||jsonb_build_object('amount',v_amount);
  elsif v_type_name='tuning' then prize:=prize||jsonb_build_object('part',v_part);
  elsif v_type_name='car' then prize:=prize||jsonb_build_object('carId',v_car);
  elsif v_type_name='plate' then prize:=prize||jsonb_build_object('plate',jsonb_build_object('uid','srv_'||replace(gen_random_uuid()::text,'-',''),'text',v_plate,'rarity',v_rarity,'series','SERVER CASE','value',v_value,'limited',v_rarity in ('legendary','mythic')));
  end if;

  update public.case_pity set bronze=pity.bronze,silver=pity.silver,gold=pity.gold,gold_car=pity.gold_car,updated_at=now() where owner_uid=auth.uid();
  insert into public.case_rolls(owner_uid,player_id,case_id,price,prize) values(auth.uid(),me.id,p_case_id,v_price,prize) returning id into v_id;
  roll_id:=v_id;price:=v_price;return next;
end;$$;
grant execute on function public.autosyndicate_roll_case(text,jsonb) to authenticated;

create or replace function public.autosyndicate_claim_case_roll(p_roll_id uuid)
returns boolean
language plpgsql security definer set search_path=public
as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  update public.case_rolls set claimed_at=coalesce(claimed_at,now()) where id=p_roll_id and owner_uid=auth.uid();
  if not found then raise exception 'case roll not found'; end if;
  return true;
end;$$;
grant execute on function public.autosyndicate_claim_case_roll(uuid) to authenticated;

commit;
